### ISSUE TITLE
Add additional denied namespaces as an OSD add on

### ISSUE THREAD

**Issue by maleck13** [openshift/rbac-permissions-operator#49]
As an add on to an OSD cluster, I have a use case where I would like to protect certain namespaces that my add on creates from the dedicated-admins group. Modifying the dedicated-admins SubjectPermissions resource does not appear to work as it quickly gets reset (perhaps by this https://github.com/openshift/managed-cluster-config/blob/master/deploy/rbac-permissions-operator-config/00-dedicated-admins.SubjectPermission.yaml). 
Is there a way for an add on to specify an additional regex for protecting the namespaces it creates? Could this be achieved in someway with a new SubjectPermissions resource?

**Comment by sam-nguyen7** [comment]
@maleck13 are you testing this on a stage cluster or another environment?

**Comment by maleck13** [comment]
a stage cluster

**Comment by sam-nguyen7** [comment]
@maleck13 sorry for the late response on this. This operator generates a SelectorSyncSet which facilitates its deployment to Hive. In order to test this operator on a stage cluster, you would need to disable SelectorSyncSet on hive then you should be able to modify the dedicated-admins SubjectPermissions resources, or add another SubjectPermission CR. 
Another way to test this is to deploy the operator manually through CRC (https://code-ready.github.io/crc/)
Let me know if I can help further.

**Comment by matskiv** [comment]
@sam-nguyen7 Hi, I am from the same team as @maleck13 

I tried to create additional SubjectPermission CR, which referenced same roles as "dedicated-admins" SubjectPermission resource, but added also our namespace into `spec.namespacesDeniedRegex`, and the `admin-dedicated-admins` RoleBinding for our project was created anyway. So seems like there is no aggregation of the rules from multiple SubjectPermission resources, and creating another SubjectPermission resource isn't the way to go for our use case (protecting additional namespaces from dedicated-admins group).

So what would be the correct way to get our regexp into namespacesDeniedRegex? And we are looking for a way to get this into production as well (once our addon is ready for GA).

**Comment by maleck13** [comment]
@matskiv Sorry for not updating you, but at the moment there is discussion around adding a new addons prefix so that addons can create protected namespaces by conforming to the new pattern

**Comment by sam-nguyen7** [comment]
@matskiv @maleck13 the way to get your regexp into the CR would be for us to do it for you. Please open a JIRA card and we an communicate through that channel.
